version: "3.8"
services:

# ==================================================== DB_MONGO ====================================================
# To be commented
#
#
  mongo:
# image
    image: mongo
# container_name
    container_name: mongo_container
# build
# networks
    networks:
      - backend
# volumes
    volumes:
      - type: bind
        source: ${MONGO_DATA_VOL}
        target: /data/db
# ports
    ports:
      - ${MONGO_PORT}:27017
# environment
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
# depends_on
# command
# entrypoint
# healthcheck
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
# configs
# secrets
# deploy
# restart
    restart: unless-stopped

# ----------------------------------------------------
  mongo-express:
# image
    image: mongo-express
# container_name
    container_name: mongo-express_container
# build
# networks
    networks:
      - backend
# volumes
# ports
    ports:
      - ${ME_PORT}:8081
# environment
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
# depends_on
# command
# entrypoint
# healthcheck
# configs
# secrets
# deploy
# restart  
    restart: unless-stopped
# ---------------------------------------------------- DB_MONGO ----------------------------------------------------

networks:
  frontend:
    driver: bridge         
  backend:
    driver: bridge